file(GLOB_RECURSE SOURCES_CORE_ENGINE "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
set(SOURCES_CORE_ENGINE ${SOURCES_CORE_ENGINE} PARENT_SCOPE)

file(GLOB_RECURSE SOURCE_CORE_EDITOR "${CMAKE_CURRENT_SOURCE_DIR}/core_editor/*.cpp")
set(SOURCE_CORE_EDITOR ${SOURCE_CORE_EDITOR} PARENT_SCOPE)

add_subdirectory(core)
set(SOURCES_CORE ${SOURCES_CORE} PARENT_SCOPE)