add_subdirectory(cpp)
# add_subdirectory(assembly)
# add_subdirectory(python)

set(SOURCES ${MAIN_PROJECT_SOURCE} PARENT_SCOPE)
set(SOURCES_CORE ${SOURCE_CORE} PARENT_SCOPE)
set(SOURCES_CORE_ENGINE ${SOURCE_CORE_ENGINE} PARENT_SCOPE)
set(SOURCES_UI ${SOURCE_UI} PARENT_SCOPE)
set(SOURCES_VULKAN ${SOURCE_VULKAN} PARENT_SCOPE)
set(VIEWPORT_SOURCES ${VIEWPORT_SOURCE} PARENT_SCOPE)